/**
 * MIRROR — MiniKit Configuration
 *
 * Single source of truth for:
 * - Farcaster manifest (/.well-known/farcaster.json)
 * - fc:miniapp embed meta tag (layout.tsx)
 * - OG / splash asset references
 *
 * After deploying to Vercel:
 * 1. Go to https://www.base.dev/preview?tab=account
 * 2. Paste your domain in App URL field → Submit
 * 3. Copy the three accountAssociation values into .env.local
 * 4. Redeploy
 */

const ROOT_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://mirror.baised.xyz';

export const minikitConfig = {
  accountAssociation: {
    // Generated by: https://www.base.dev/preview?tab=account
    // Add domain → sign with Farcaster account → copy values below (or into .env.local)
    header:    process.env.FARCASTER_HEADER    ?? '',
    payload:   process.env.FARCASTER_PAYLOAD   ?? '',
    signature: process.env.FARCASTER_SIGNATURE ?? '',
  },

  miniapp: {
    version:              '1',
    name:                 'MIRROR',
    subtitle:             'Social Copy Trade',
    description:          'One-tap copy trades from wallets you follow on Farcaster. Gasless. No popups.',
    tagline:              'One tap. One trade. No gas.',

    // Assets — dynamically generated via /api/og (edge ImageResponse)
    iconUrl:              `${ROOT_URL}/api/og?type=icon`,
    splashImageUrl:       `${ROOT_URL}/api/og?type=splash`,
    splashBackgroundColor:'#000000',
    heroImageUrl:         `${ROOT_URL}/api/og`,
    screenshotUrls:       [`${ROOT_URL}/api/og`],

    // OG
    ogTitle:              'MIRROR — Social Copy Trade',
    ogDescription:        'One-tap copy trades from wallets you follow. Zero gas. Zero popups.',
    ogImageUrl:           `${ROOT_URL}/api/og`,

    // URLs
    homeUrl:              ROOT_URL,
    webhookUrl:           `${ROOT_URL}/api/webhook`,

    // Discovery
    primaryCategory:      'finance',
    tags:                 ['trading', 'defi', 'copy-trade', 'base', 'farcaster'],

    // Chain requirements
    requiredChains:       ['eip155:8453'], // Base mainnet (CAIP-2)

    // Capability declarations
    requiredCapabilities: ['wallet.getEthereumProvider'],
    optionalCapabilities: ['actions.composeCast', 'actions.addMiniApp', 'wallet.addSessionKey'],
  },
} as const;
